<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class KabupatenSeeder extends Seeder
{
    public function run()
    {
        $db = \Config\Database::connect();
        $builder = $db->table('kabupaten');

        // Ambil mapping provinsi berdasarkan kode_kemendagri (2 digit)
        $provList = $db->table('provinsi')->get()->getResultArray();
        $provMap = [];
        foreach ($provList as $p) {
            $provMap[$p['kode_kemendagri']] = [
                'id'   => (int) $p['id'],
                'nama' => $p['nama'],
            ];
        }

        // Daftar lengkap 514 Kabupaten dan Kota di Indonesia sesuai Permendagri / Kepmendagri
        $dataKabupaten = [
            // 11 - ACEH (23)
            ['kode' => '11.01', 'nama' => 'Kabupaten Aceh Selatan'],
            ['kode' => '11.02', 'nama' => 'Kabupaten Aceh Tenggara'],
            ['kode' => '11.03', 'nama' => 'Kabupaten Aceh Timur'],
            ['kode' => '11.04', 'nama' => 'Kabupaten Aceh Tengah'],
            ['kode' => '11.05', 'nama' => 'Kabupaten Aceh Barat'],
            ['kode' => '11.06', 'nama' => 'Kabupaten Aceh Besar'],
            ['kode' => '11.07', 'nama' => 'Kabupaten Pidie'],
            ['kode' => '11.08', 'nama' => 'Kabupaten Aceh Utara'],
            ['kode' => '11.09', 'nama' => 'Kabupaten Simeulue'],
            ['kode' => '11.10', 'nama' => 'Kabupaten Aceh Singkil'],
            ['kode' => '11.11', 'nama' => 'Kabupaten Bireuen'],
            ['kode' => '11.12', 'nama' => 'Kabupaten Aceh Barat Daya'],
            ['kode' => '11.13', 'nama' => 'Kabupaten Gayo Lues'],
            ['kode' => '11.14', 'nama' => 'Kabupaten Aceh Tamiang'],
            ['kode' => '11.15', 'nama' => 'Kabupaten Nagan Raya'],
            ['kode' => '11.16', 'nama' => 'Kabupaten Aceh Jaya'],
            ['kode' => '11.17', 'nama' => 'Kabupaten Bener Meriah'],
            ['kode' => '11.18', 'nama' => 'Kabupaten Pidie Jaya'],
            ['kode' => '11.71', 'nama' => 'Kota Banda Aceh'],
            ['kode' => '11.72', 'nama' => 'Kota Sabang'],
            ['kode' => '11.73', 'nama' => 'Kota Langsa'],
            ['kode' => '11.74', 'nama' => 'Kota Lhokseumawe'],
            ['kode' => '11.75', 'nama' => 'Kota Subulussalam'],

            // 12 - SUMATERA UTARA (33)
            ['kode' => '12.01', 'nama' => 'Kabupaten Nias'],
            ['kode' => '12.02', 'nama' => 'Kabupaten Mandailing Natal'],
            ['kode' => '12.03', 'nama' => 'Kabupaten Tapanuli Selatan'],
            ['kode' => '12.04', 'nama' => 'Kabupaten Tapanuli Tengah'],
            ['kode' => '12.05', 'nama' => 'Kabupaten Tapanuli Utara'],
            ['kode' => '12.06', 'nama' => 'Kabupaten Toba'],
            ['kode' => '12.07', 'nama' => 'Kabupaten Labuhanbatu'],
            ['kode' => '12.08', 'nama' => 'Kabupaten Asahan'],
            ['kode' => '12.09', 'nama' => 'Kabupaten Simalungun'],
            ['kode' => '12.10', 'nama' => 'Kabupaten Dairi'],
            ['kode' => '12.11', 'nama' => 'Kabupaten Karo'],
            ['kode' => '12.12', 'nama' => 'Kabupaten Deli Serdang'],
            ['kode' => '12.13', 'nama' => 'Kabupaten Langkat'],
            ['kode' => '12.14', 'nama' => 'Kabupaten Nias Selatan'],
            ['kode' => '12.15', 'nama' => 'Kabupaten Humbang Hasundutan'],
            ['kode' => '12.16', 'nama' => 'Kabupaten Pakpak Bharat'],
            ['kode' => '12.17', 'nama' => 'Kabupaten Samosir'],
            ['kode' => '12.18', 'nama' => 'Kabupaten Serdang Bedagai'],
            ['kode' => '12.19', 'nama' => 'Kabupaten Batu Bara'],
            ['kode' => '12.20', 'nama' => 'Kabupaten Padang Lawas Utara'],
            ['kode' => '12.21', 'nama' => 'Kabupaten Padang Lawas'],
            ['kode' => '12.22', 'nama' => 'Kabupaten Labuhanbatu Selatan'],
            ['kode' => '12.23', 'nama' => 'Kabupaten Labuhanbatu Utara'],
            ['kode' => '12.24', 'nama' => 'Kabupaten Nias Utara'],
            ['kode' => '12.25', 'nama' => 'Kabupaten Nias Barat'],
            ['kode' => '12.71', 'nama' => 'Kota Sibolga'],
            ['kode' => '12.72', 'nama' => 'Kota Tanjung Balai'],
            ['kode' => '12.73', 'nama' => 'Kota Pematang Siantar'],
            ['kode' => '12.74', 'nama' => 'Kota Tebing Tinggi'],
            ['kode' => '12.75', 'nama' => 'Kota Medan'],
            ['kode' => '12.76', 'nama' => 'Kota Binjai'],
            ['kode' => '12.77', 'nama' => 'Kota Padangsidimpuan'],
            ['kode' => '12.78', 'nama' => 'Kota Gunungsitoli'],

            // 13 - SUMATERA BARAT (19)
            ['kode' => '13.01', 'nama' => 'Kabupaten Kepulauan Mentawai'],
            ['kode' => '13.02', 'nama' => 'Kabupaten Pesisir Selatan'],
            ['kode' => '13.03', 'nama' => 'Kabupaten Solok'],
            ['kode' => '13.04', 'nama' => 'Kabupaten Sijunjung'],
            ['kode' => '13.05', 'nama' => 'Kabupaten Tanah Datar'],
            ['kode' => '13.06', 'nama' => 'Kabupaten Padang Pariaman'],
            ['kode' => '13.07', 'nama' => 'Kabupaten Agam'],
            ['kode' => '13.08', 'nama' => 'Kabupaten Lima Puluh Kota'],
            ['kode' => '13.09', 'nama' => 'Kabupaten Pasaman'],
            ['kode' => '13.10', 'nama' => 'Kabupaten Solok Selatan'],
            ['kode' => '13.11', 'nama' => 'Kabupaten Dharmasraya'],
            ['kode' => '13.12', 'nama' => 'Kabupaten Pasaman Barat'],
            ['kode' => '13.71', 'nama' => 'Kota Padang'],
            ['kode' => '13.72', 'nama' => 'Kota Solok'],
            ['kode' => '13.73', 'nama' => 'Kota Sawahlunto'],
            ['kode' => '13.74', 'nama' => 'Kota Padang Panjang'],
            ['kode' => '13.75', 'nama' => 'Kota Bukittinggi'],
            ['kode' => '13.76', 'nama' => 'Kota Payakumbuh'],
            ['kode' => '13.77', 'nama' => 'Kota Pariaman'],

            // 14 - RIAU (12)
            ['kode' => '14.01', 'nama' => 'Kabupaten Kuantan Singingi'],
            ['kode' => '14.02', 'nama' => 'Kabupaten Indragiri Hulu'],
            ['kode' => '14.03', 'nama' => 'Kabupaten Indragiri Hilir'],
            ['kode' => '14.04', 'nama' => 'Kabupaten Pelalawan'],
            ['kode' => '14.05', 'nama' => 'Kabupaten Siak'],
            ['kode' => '14.06', 'nama' => 'Kabupaten Kampar'],
            ['kode' => '14.07', 'nama' => 'Kabupaten Rokan Hulu'],
            ['kode' => '14.08', 'nama' => 'Kabupaten Bengkalis'],
            ['kode' => '14.09', 'nama' => 'Kabupaten Rokan Hilir'],
            ['kode' => '14.10', 'nama' => 'Kabupaten Kepulauan Meranti'],
            ['kode' => '14.71', 'nama' => 'Kota Pekanbaru'],
            ['kode' => '14.72', 'nama' => 'Kota Dumai'],

            // 15 - JAMBI (11)
            ['kode' => '15.01', 'nama' => 'Kabupaten Kerinci'],
            ['kode' => '15.02', 'nama' => 'Kabupaten Merangin'],
            ['kode' => '15.03', 'nama' => 'Kabupaten Sarolangun'],
            ['kode' => '15.04', 'nama' => 'Kabupaten Batanghari'],
            ['kode' => '15.05', 'nama' => 'Kabupaten Muaro Jambi'],
            ['kode' => '15.06', 'nama' => 'Kabupaten Tanjung Jabung Barat'],
            ['kode' => '15.07', 'nama' => 'Kabupaten Tanjung Jabung Timur'],
            ['kode' => '15.08', 'nama' => 'Kabupaten Bungo'],
            ['kode' => '15.09', 'nama' => 'Kabupaten Tebo'],
            ['kode' => '15.71', 'nama' => 'Kota Jambi'],
            ['kode' => '15.72', 'nama' => 'Kota Sungai Penuh'],

            // 16 - SUMATERA SELATAN (17)
            ['kode' => '16.01', 'nama' => 'Kabupaten Ogan Komering Ulu'],
            ['kode' => '16.02', 'nama' => 'Kabupaten Ogan Komering Ilir'],
            ['kode' => '16.03', 'nama' => 'Kabupaten Muara Enim'],
            ['kode' => '16.04', 'nama' => 'Kabupaten Lahat'],
            ['kode' => '16.05', 'nama' => 'Kabupaten Musi Rawas'],
            ['kode' => '16.06', 'nama' => 'Kabupaten Musi Banyuasin'],
            ['kode' => '16.07', 'nama' => 'Kabupaten Banyuasin'],
            ['kode' => '16.08', 'nama' => 'Kabupaten Ogan Komering Ulu Selatan'],
            ['kode' => '16.09', 'nama' => 'Kabupaten Ogan Komering Ulu Timur'],
            ['kode' => '16.10', 'nama' => 'Kabupaten Ogan Ilir'],
            ['kode' => '16.11', 'nama' => 'Kabupaten Empat Lawang'],
            ['kode' => '16.12', 'nama' => 'Kabupaten Penukal Abab Lematang Ilir'],
            ['kode' => '16.13', 'nama' => 'Kabupaten Musi Rawas Utara'],
            ['kode' => '16.71', 'nama' => 'Kota Palembang'],
            ['kode' => '16.72', 'nama' => 'Kota Prabumulih'],
            ['kode' => '16.73', 'nama' => 'Kota Pagar Alam'],
            ['kode' => '16.74', 'nama' => 'Kota Lubuklinggau'],

            // 17 - BENGKULU (10)
            ['kode' => '17.01', 'nama' => 'Kabupaten Bengkulu Selatan'],
            ['kode' => '17.02', 'nama' => 'Kabupaten Rejang Lebong'],
            ['kode' => '17.03', 'nama' => 'Kabupaten Bengkulu Utara'],
            ['kode' => '17.04', 'nama' => 'Kabupaten Kaur'],
            ['kode' => '17.05', 'nama' => 'Kabupaten Seluma'],
            ['kode' => '17.06', 'nama' => 'Kabupaten Mukomuko'],
            ['kode' => '17.07', 'nama' => 'Kabupaten Lebong'],
            ['kode' => '17.08', 'nama' => 'Kabupaten Kepahiang'],
            ['kode' => '17.09', 'nama' => 'Kabupaten Bengkulu Tengah'],
            ['kode' => '17.71', 'nama' => 'Kota Bengkulu'],

            // 18 - LAMPUNG (15)
            ['kode' => '18.01', 'nama' => 'Kabupaten Lampung Barat'],
            ['kode' => '18.02', 'nama' => 'Kabupaten Tanggamus'],
            ['kode' => '18.03', 'nama' => 'Kabupaten Lampung Selatan'],
            ['kode' => '18.04', 'nama' => 'Kabupaten Lampung Timur'],
            ['kode' => '18.05', 'nama' => 'Kabupaten Lampung Tengah'],
            ['kode' => '18.06', 'nama' => 'Kabupaten Lampung Utara'],
            ['kode' => '18.07', 'nama' => 'Kabupaten Way Kanan'],
            ['kode' => '18.08', 'nama' => 'Kabupaten Tulangbawang'],
            ['kode' => '18.09', 'nama' => 'Kabupaten Pesawaran'],
            ['kode' => '18.10', 'nama' => 'Kabupaten Pringsewu'],
            ['kode' => '18.11', 'nama' => 'Kabupaten Mesuji'],
            ['kode' => '18.12', 'nama' => 'Kabupaten Tulang Bawang Barat'],
            ['kode' => '18.13', 'nama' => 'Kabupaten Pesisir Barat'],
            ['kode' => '18.71', 'nama' => 'Kota Bandar Lampung'],
            ['kode' => '18.72', 'nama' => 'Kota Metro'],

            // 19 - KEPULAUAN BANGKA BELITUNG (7)
            ['kode' => '19.01', 'nama' => 'Kabupaten Bangka'],
            ['kode' => '19.02', 'nama' => 'Kabupaten Belitung'],
            ['kode' => '19.03', 'nama' => 'Kabupaten Bangka Barat'],
            ['kode' => '19.04', 'nama' => 'Kabupaten Bangka Tengah'],
            ['kode' => '19.05', 'nama' => 'Kabupaten Bangka Selatan'],
            ['kode' => '19.06', 'nama' => 'Kabupaten Belitung Timur'],
            ['kode' => '19.71', 'nama' => 'Kota Pangkal Pinang'],

            // 21 - KEPULAUAN RIAU (7)
            ['kode' => '21.01', 'nama' => 'Kabupaten Karimun'],
            ['kode' => '21.02', 'nama' => 'Kabupaten Bintan'],
            ['kode' => '21.03', 'nama' => 'Kabupaten Natuna'],
            ['kode' => '21.04', 'nama' => 'Kabupaten Lingga'],
            ['kode' => '21.05', 'nama' => 'Kabupaten Kepulauan Anambas'],
            ['kode' => '21.71', 'nama' => 'Kota Batam'],
            ['kode' => '21.72', 'nama' => 'Kota Tanjung Pinang'],

            // 31 - DKI JAKARTA (6)
            ['kode' => '31.01', 'nama' => 'Kabupaten Administrasi Kepulauan Seribu'],
            ['kode' => '31.71', 'nama' => 'Kota Administrasi Jakarta Selatan'],
            ['kode' => '31.72', 'nama' => 'Kota Administrasi Jakarta Timur'],
            ['kode' => '31.73', 'nama' => 'Kota Administrasi Jakarta Pusat'],
            ['kode' => '31.74', 'nama' => 'Kota Administrasi Jakarta Barat'],
            ['kode' => '31.75', 'nama' => 'Kota Administrasi Jakarta Utara'],

            // 32 - JAWA BARAT (27)
            ['kode' => '32.01', 'nama' => 'Kabupaten Bogor'],
            ['kode' => '32.02', 'nama' => 'Kabupaten Sukabumi'],
            ['kode' => '32.03', 'nama' => 'Kabupaten Cianjur'],
            ['kode' => '32.04', 'nama' => 'Kabupaten Bandung'],
            ['kode' => '32.05', 'nama' => 'Kabupaten Garut'],
            ['kode' => '32.06', 'nama' => 'Kabupaten Tasikmalaya'],
            ['kode' => '32.07', 'nama' => 'Kabupaten Ciamis'],
            ['kode' => '32.08', 'nama' => 'Kabupaten Kuningan'],
            ['kode' => '32.09', 'nama' => 'Kabupaten Cirebon'],
            ['kode' => '32.10', 'nama' => 'Kabupaten Majalengka'],
            ['kode' => '32.11', 'nama' => 'Kabupaten Sumedang'],
            ['kode' => '32.12', 'nama' => 'Kabupaten Indramayu'],
            ['kode' => '32.13', 'nama' => 'Kabupaten Subang'],
            ['kode' => '32.14', 'nama' => 'Kabupaten Purwakarta'],
            ['kode' => '32.15', 'nama' => 'Kabupaten Karawang'],
            ['kode' => '32.16', 'nama' => 'Kabupaten Bekasi'],
            ['kode' => '32.17', 'nama' => 'Kabupaten Bandung Barat'],
            ['kode' => '32.18', 'nama' => 'Kabupaten Pangandaran'],
            ['kode' => '32.71', 'nama' => 'Kota Bogor'],
            ['kode' => '32.72', 'nama' => 'Kota Sukabumi'],
            ['kode' => '32.73', 'nama' => 'Kota Bandung'],
            ['kode' => '32.74', 'nama' => 'Kota Cirebon'],
            ['kode' => '32.75', 'nama' => 'Kota Bekasi'],
            ['kode' => '32.76', 'nama' => 'Kota Depok'],
            ['kode' => '32.77', 'nama' => 'Kota Cimahi'],
            ['kode' => '32.78', 'nama' => 'Kota Tasikmalaya'],
            ['kode' => '32.79', 'nama' => 'Kota Banjar'],

            // 33 - JAWA TENGAH (35)
            ['kode' => '33.01', 'nama' => 'Kabupaten Cilacap'],
            ['kode' => '33.02', 'nama' => 'Kabupaten Banyumas'],
            ['kode' => '33.03', 'nama' => 'Kabupaten Purbalingga'],
            ['kode' => '33.04', 'nama' => 'Kabupaten Banjarnegara'],
            ['kode' => '33.05', 'nama' => 'Kabupaten Kebumen'],
            ['kode' => '33.06', 'nama' => 'Kabupaten Purworejo'],
            ['kode' => '33.07', 'nama' => 'Kabupaten Wonosobo'],
            ['kode' => '33.08', 'nama' => 'Kabupaten Magelang'],
            ['kode' => '33.09', 'nama' => 'Kabupaten Boyolali'],
            ['kode' => '33.10', 'nama' => 'Kabupaten Klaten'],
            ['kode' => '33.11', 'nama' => 'Kabupaten Sukoharjo'],
            ['kode' => '33.12', 'nama' => 'Kabupaten Wonogiri'],
            ['kode' => '33.13', 'nama' => 'Kabupaten Karanganyar'],
            ['kode' => '33.14', 'nama' => 'Kabupaten Sragen'],
            ['kode' => '33.15', 'nama' => 'Kabupaten Grobogan'],
            ['kode' => '33.16', 'nama' => 'Kabupaten Blora'],
            ['kode' => '33.17', 'nama' => 'Kabupaten Rembang'],
            ['kode' => '33.18', 'nama' => 'Kabupaten Pati'],
            ['kode' => '33.19', 'nama' => 'Kabupaten Kudus'],
            ['kode' => '33.20', 'nama' => 'Kabupaten Jepara'],
            ['kode' => '33.21', 'nama' => 'Kabupaten Demak'],
            ['kode' => '33.22', 'nama' => 'Kabupaten Semarang'],
            ['kode' => '33.23', 'nama' => 'Kabupaten Temanggung'],
            ['kode' => '33.24', 'nama' => 'Kabupaten Kendal'],
            ['kode' => '33.25', 'nama' => 'Kabupaten Batang'],
            ['kode' => '33.26', 'nama' => 'Kabupaten Pekalongan'],
            ['kode' => '33.27', 'nama' => 'Kabupaten Pemalang'],
            ['kode' => '33.28', 'nama' => 'Kabupaten Tegal'],
            ['kode' => '33.29', 'nama' => 'Kabupaten Brebes'],
            ['kode' => '33.71', 'nama' => 'Kota Magelang'],
            ['kode' => '33.72', 'nama' => 'Kota Surakarta'],
            ['kode' => '33.73', 'nama' => 'Kota Salatiga'],
            ['kode' => '33.74', 'nama' => 'Kota Semarang'],
            ['kode' => '33.75', 'nama' => 'Kota Pekalongan'],
            ['kode' => '33.76', 'nama' => 'Kota Tegal'],

            // 34 - DAERAH ISTIMEWA YOGYAKARTA (5)
            ['kode' => '34.01', 'nama' => 'Kabupaten Kulon Progo'],
            ['kode' => '34.02', 'nama' => 'Kabupaten Bantul'],
            ['kode' => '34.03', 'nama' => 'Kabupaten Gunungkidul'],
            ['kode' => '34.04', 'nama' => 'Kabupaten Sleman'],
            ['kode' => '34.71', 'nama' => 'Kota Yogyakarta'],

            // 35 - JAWA TIMUR (38)
            ['kode' => '35.01', 'nama' => 'Kabupaten Pacitan'],
            ['kode' => '35.02', 'nama' => 'Kabupaten Ponorogo'],
            ['kode' => '35.03', 'nama' => 'Kabupaten Trenggalek'],
            ['kode' => '35.04', 'nama' => 'Kabupaten Tulungagung'],
            ['kode' => '35.05', 'nama' => 'Kabupaten Blitar'],
            ['kode' => '35.06', 'nama' => 'Kabupaten Kediri'],
            ['kode' => '35.07', 'nama' => 'Kabupaten Malang'],
            ['kode' => '35.08', 'nama' => 'Kabupaten Lumajang'],
            ['kode' => '35.09', 'nama' => 'Kabupaten Jember'],
            ['kode' => '35.10', 'nama' => 'Kabupaten Banyuwangi'],
            ['kode' => '35.11', 'nama' => 'Kabupaten Bondowoso'],
            ['kode' => '35.12', 'nama' => 'Kabupaten Situbondo'],
            ['kode' => '35.13', 'nama' => 'Kabupaten Probolinggo'],
            ['kode' => '35.14', 'nama' => 'Kabupaten Pasuruan'],
            ['kode' => '35.15', 'nama' => 'Kabupaten Sidoarjo'],
            ['kode' => '35.16', 'nama' => 'Kabupaten Mojokerto'],
            ['kode' => '35.17', 'nama' => 'Kabupaten Jombang'],
            ['kode' => '35.18', 'nama' => 'Kabupaten Nganjuk'],
            ['kode' => '35.19', 'nama' => 'Kabupaten Madiun'],
            ['kode' => '35.20', 'nama' => 'Kabupaten Magetan'],
            ['kode' => '35.21', 'nama' => 'Kabupaten Ngawi'],
            ['kode' => '35.22', 'nama' => 'Kabupaten Bojonegoro'],
            ['kode' => '35.23', 'nama' => 'Kabupaten Tuban'],
            ['kode' => '35.24', 'nama' => 'Kabupaten Lamongan'],
            ['kode' => '35.25', 'nama' => 'Kabupaten Gresik'],
            ['kode' => '35.26', 'nama' => 'Kabupaten Bangkalan'],
            ['kode' => '35.27', 'nama' => 'Kabupaten Sampang'],
            ['kode' => '35.28', 'nama' => 'Kabupaten Pamekasan'],
            ['kode' => '35.29', 'nama' => 'Kabupaten Sumenep'],
            ['kode' => '35.71', 'nama' => 'Kota Kediri'],
            ['kode' => '35.72', 'nama' => 'Kota Blitar'],
            ['kode' => '35.73', 'nama' => 'Kota Malang'],
            ['kode' => '35.74', 'nama' => 'Kota Probolinggo'],
            ['kode' => '35.75', 'nama' => 'Kota Pasuruan'],
            ['kode' => '35.76', 'nama' => 'Kota Mojokerto'],
            ['kode' => '35.77', 'nama' => 'Kota Madiun'],
            ['kode' => '35.78', 'nama' => 'Kota Surabaya'],
            ['kode' => '35.79', 'nama' => 'Kota Batu'],

            // 36 - BANTEN (8)
            ['kode' => '36.01', 'nama' => 'Kabupaten Pandeglang'],
            ['kode' => '36.02', 'nama' => 'Kabupaten Lebak'],
            ['kode' => '36.03', 'nama' => 'Kabupaten Tangerang'],
            ['kode' => '36.04', 'nama' => 'Kabupaten Serang'],
            ['kode' => '36.71', 'nama' => 'Kota Tangerang'],
            ['kode' => '36.72', 'nama' => 'Kota Cilegon'],
            ['kode' => '36.73', 'nama' => 'Kota Serang'],
            ['kode' => '36.74', 'nama' => 'Kota Tangerang Selatan'],

            // 51 - BALI (9)
            ['kode' => '51.01', 'nama' => 'Kabupaten Jembrana'],
            ['kode' => '51.02', 'nama' => 'Kabupaten Tabanan'],
            ['kode' => '51.03', 'nama' => 'Kabupaten Badung'],
            ['kode' => '51.04', 'nama' => 'Kabupaten Gianyar'],
            ['kode' => '51.05', 'nama' => 'Kabupaten Klungkung'],
            ['kode' => '51.06', 'nama' => 'Kabupaten Bangli'],
            ['kode' => '51.07', 'nama' => 'Kabupaten Karangasem'],
            ['kode' => '51.08', 'nama' => 'Kabupaten Buleleng'],
            ['kode' => '51.71', 'nama' => 'Kota Denpasar'],

            // 52 - NUSA TENGGARA BARAT (10)
            ['kode' => '52.01', 'nama' => 'Kabupaten Lombok Barat'],
            ['kode' => '52.02', 'nama' => 'Kabupaten Lombok Tengah'],
            ['kode' => '52.03', 'nama' => 'Kabupaten Lombok Timur'],
            ['kode' => '52.04', 'nama' => 'Kabupaten Sumbawa'],
            ['kode' => '52.05', 'nama' => 'Kabupaten Dompu'],
            ['kode' => '52.06', 'nama' => 'Kabupaten Bima'],
            ['kode' => '52.07', 'nama' => 'Kabupaten Sumbawa Barat'],
            ['kode' => '52.08', 'nama' => 'Kabupaten Lombok Utara'],
            ['kode' => '52.71', 'nama' => 'Kota Mataram'],
            ['kode' => '52.72', 'nama' => 'Kota Bima'],

            // 53 - NUSA TENGGARA TIMUR (22)
            ['kode' => '53.01', 'nama' => 'Kabupaten Sumba Barat'],
            ['kode' => '53.02', 'nama' => 'Kabupaten Sumba Timur'],
            ['kode' => '53.03', 'nama' => 'Kabupaten Kupang'],
            ['kode' => '53.04', 'nama' => 'Kabupaten Timor Tengah Selatan'],
            ['kode' => '53.05', 'nama' => 'Kabupaten Timor Tengah Utara'],
            ['kode' => '53.06', 'nama' => 'Kabupaten Belu'],
            ['kode' => '53.07', 'nama' => 'Kabupaten Alor'],
            ['kode' => '53.08', 'nama' => 'Kabupaten Lembata'],
            ['kode' => '53.09', 'nama' => 'Kabupaten Flores Timur'],
            ['kode' => '53.10', 'nama' => 'Kabupaten Sikka'],
            ['kode' => '53.11', 'nama' => 'Kabupaten Ende'],
            ['kode' => '53.12', 'nama' => 'Kabupaten Ngada'],
            ['kode' => '53.13', 'nama' => 'Kabupaten Manggarai'],
            ['kode' => '53.14', 'nama' => 'Kabupaten Rote Ndao'],
            ['kode' => '53.15', 'nama' => 'Kabupaten Manggarai Barat'],
            ['kode' => '53.16', 'nama' => 'Kabupaten Sumba Tengah'],
            ['kode' => '53.17', 'nama' => 'Kabupaten Sumba Barat Daya'],
            ['kode' => '53.18', 'nama' => 'Kabupaten Nagekeo'],
            ['kode' => '53.19', 'nama' => 'Kabupaten Manggarai Timur'],
            ['kode' => '53.20', 'nama' => 'Kabupaten Sabu Raijua'],
            ['kode' => '53.21', 'nama' => 'Kabupaten Malaka'],
            ['kode' => '53.71', 'nama' => 'Kota Kupang'],

            // 61 - KALIMANTAN BARAT (14)
            ['kode' => '61.01', 'nama' => 'Kabupaten Sambas'],
            ['kode' => '61.02', 'nama' => 'Kabupaten Bengkayang'],
            ['kode' => '61.03', 'nama' => 'Kabupaten Landak'],
            ['kode' => '61.04', 'nama' => 'Kabupaten Mempawah'],
            ['kode' => '61.05', 'nama' => 'Kabupaten Sanggau'],
            ['kode' => '61.06', 'nama' => 'Kabupaten Ketapang'],
            ['kode' => '61.07', 'nama' => 'Kabupaten Sintang'],
            ['kode' => '61.08', 'nama' => 'Kabupaten Kapuas Hulu'],
            ['kode' => '61.09', 'nama' => 'Kabupaten Sekadau'],
            ['kode' => '61.10', 'nama' => 'Kabupaten Melawi'],
            ['kode' => '61.11', 'nama' => 'Kabupaten Kayong Utara'],
            ['kode' => '61.12', 'nama' => 'Kabupaten Kubu Raya'],
            ['kode' => '61.71', 'nama' => 'Kota Pontianak'],
            ['kode' => '61.72', 'nama' => 'Kota Singkawang'],

            // 62 - KALIMANTAN TENGAH (14)
            ['kode' => '62.01', 'nama' => 'Kabupaten Kotawaringin Barat'],
            ['kode' => '62.02', 'nama' => 'Kabupaten Kotawaringin Timur'],
            ['kode' => '62.03', 'nama' => 'Kabupaten Kapuas'],
            ['kode' => '62.04', 'nama' => 'Kabupaten Barito Selatan'],
            ['kode' => '62.05', 'nama' => 'Kabupaten Barito Utara'],
            ['kode' => '62.06', 'nama' => 'Kabupaten Sukamara'],
            ['kode' => '62.07', 'nama' => 'Kabupaten Lamandau'],
            ['kode' => '62.08', 'nama' => 'Kabupaten Seruyan'],
            ['kode' => '62.09', 'nama' => 'Kabupaten Katingan'],
            ['kode' => '62.10', 'nama' => 'Kabupaten Pulang Pisau'],
            ['kode' => '62.11', 'nama' => 'Kabupaten Gunung Mas'],
            ['kode' => '62.12', 'nama' => 'Kabupaten Barito Timur'],
            ['kode' => '62.13', 'nama' => 'Kabupaten Murung Raya'],
            ['kode' => '62.71', 'nama' => 'Kota Palangka Raya'],

            // 63 - KALIMANTAN SELATAN (13)
            ['kode' => '63.01', 'nama' => 'Kabupaten Tanah Laut'],
            ['kode' => '63.02', 'nama' => 'Kabupaten Kotabaru'],
            ['kode' => '63.03', 'nama' => 'Kabupaten Banjar'],
            ['kode' => '63.04', 'nama' => 'Kabupaten Barito Kuala'],
            ['kode' => '63.05', 'nama' => 'Kabupaten Tapin'],
            ['kode' => '63.06', 'nama' => 'Kabupaten Hulu Sungai Selatan'],
            ['kode' => '63.07', 'nama' => 'Kabupaten Hulu Sungai Tengah'],
            ['kode' => '63.08', 'nama' => 'Kabupaten Hulu Sungai Utara'],
            ['kode' => '63.09', 'nama' => 'Kabupaten Tabalong'],
            ['kode' => '63.10', 'nama' => 'Kabupaten Tanah Bumbu'],
            ['kode' => '63.11', 'nama' => 'Kabupaten Balangan'],
            ['kode' => '63.71', 'nama' => 'Kota Banjarmasin'],
            ['kode' => '63.72', 'nama' => 'Kota Banjarbaru'],

            // 64 - KALIMANTAN TIMUR (10)
            ['kode' => '64.01', 'nama' => 'Kabupaten Paser'],
            ['kode' => '64.02', 'nama' => 'Kabupaten Kutai Barat'],
            ['kode' => '64.03', 'nama' => 'Kabupaten Kutai Kartanegara'],
            ['kode' => '64.04', 'nama' => 'Kabupaten Kutai Timur'],
            ['kode' => '64.05', 'nama' => 'Kabupaten Berau'],
            ['kode' => '64.09', 'nama' => 'Kabupaten Penajam Paser Utara'],
            ['kode' => '64.11', 'nama' => 'Kabupaten Mahakam Ulu'],
            ['kode' => '64.71', 'nama' => 'Kota Balikpapan'],
            ['kode' => '64.72', 'nama' => 'Kota Samarinda'],
            ['kode' => '64.74', 'nama' => 'Kota Bontang'],

            // 65 - KALIMANTAN UTARA (5)
            ['kode' => '65.01', 'nama' => 'Kabupaten Bulungan'],
            ['kode' => '65.02', 'nama' => 'Kabupaten Malinau'],
            ['kode' => '65.03', 'nama' => 'Kabupaten Nunukan'],
            ['kode' => '65.04', 'nama' => 'Kabupaten Tana Tidung'],
            ['kode' => '65.71', 'nama' => 'Kota Tarakan'],

            // 71 - SULAWESI UTARA (15)
            ['kode' => '71.01', 'nama' => 'Kabupaten Bolaang Mongondow'],
            ['kode' => '71.02', 'nama' => 'Kabupaten Minahasa'],
            ['kode' => '71.03', 'nama' => 'Kabupaten Kepulauan Sangihe'],
            ['kode' => '71.04', 'nama' => 'Kabupaten Kepulauan Talaud'],
            ['kode' => '71.05', 'nama' => 'Kabupaten Minahasa Selatan'],
            ['kode' => '71.06', 'nama' => 'Kabupaten Minahasa Utara'],
            ['kode' => '71.07', 'nama' => 'Kabupaten Bolaang Mongondow Utara'],
            ['kode' => '71.08', 'nama' => 'Kabupaten Kepulauan Siau Tagulandang Biaro'],
            ['kode' => '71.09', 'nama' => 'Kabupaten Minahasa Tenggara'],
            ['kode' => '71.10', 'nama' => 'Kabupaten Bolaang Mongondow Selatan'],
            ['kode' => '71.11', 'nama' => 'Kabupaten Bolaang Mongondow Timur'],
            ['kode' => '71.71', 'nama' => 'Kota Manado'],
            ['kode' => '71.72', 'nama' => 'Kota Bitung'],
            ['kode' => '71.73', 'nama' => 'Kota Tomohon'],
            ['kode' => '71.74', 'nama' => 'Kota Kotamobagu'],

            // 72 - SULAWESI TENGAH (13)
            ['kode' => '72.01', 'nama' => 'Kabupaten Banggai Kepulauan'],
            ['kode' => '72.02', 'nama' => 'Kabupaten Banggai'],
            ['kode' => '72.03', 'nama' => 'Kabupaten Morowali'],
            ['kode' => '72.04', 'nama' => 'Kabupaten Poso'],
            ['kode' => '72.05', 'nama' => 'Kabupaten Donggala'],
            ['kode' => '72.06', 'nama' => 'Kabupaten Toli-Toli'],
            ['kode' => '72.07', 'nama' => 'Kabupaten Buol'],
            ['kode' => '72.08', 'nama' => 'Kabupaten Parigi Moutong'],
            ['kode' => '72.09', 'nama' => 'Kabupaten Tojo Una-Una'],
            ['kode' => '72.10', 'nama' => 'Kabupaten Sigi'],
            ['kode' => '72.11', 'nama' => 'Kabupaten Banggai Laut'],
            ['kode' => '72.12', 'nama' => 'Kabupaten Morowali Utara'],
            ['kode' => '72.71', 'nama' => 'Kota Palu'],

            // 73 - SULAWESI SELATAN (24)
            ['kode' => '73.01', 'nama' => 'Kabupaten Kepulauan Selayar'],
            ['kode' => '73.02', 'nama' => 'Kabupaten Bulukumba'],
            ['kode' => '73.03', 'nama' => 'Kabupaten Bantaeng'],
            ['kode' => '73.04', 'nama' => 'Kabupaten Jeneponto'],
            ['kode' => '73.05', 'nama' => 'Kabupaten Takalar'],
            ['kode' => '73.06', 'nama' => 'Kabupaten Gowa'],
            ['kode' => '73.07', 'nama' => 'Kabupaten Sinjai'],
            ['kode' => '73.08', 'nama' => 'Kabupaten Maros'],
            ['kode' => '73.09', 'nama' => 'Kabupaten Pangkajene dan Kepulauan'],
            ['kode' => '73.10', 'nama' => 'Kabupaten Barru'],
            ['kode' => '73.11', 'nama' => 'Kabupaten Bone'],
            ['kode' => '73.12', 'nama' => 'Kabupaten Soppeng'],
            ['kode' => '73.13', 'nama' => 'Kabupaten Wajo'],
            ['kode' => '73.14', 'nama' => 'Kabupaten Sidenreng Rappang'],
            ['kode' => '73.15', 'nama' => 'Kabupaten Pinrang'],
            ['kode' => '73.16', 'nama' => 'Kabupaten Enrekang'],
            ['kode' => '73.17', 'nama' => 'Kabupaten Luwu'],
            ['kode' => '73.18', 'nama' => 'Kabupaten Tana Toraja'],
            ['kode' => '73.22', 'nama' => 'Kabupaten Luwu Utara'],
            ['kode' => '73.24', 'nama' => 'Kabupaten Luwu Timur'],
            ['kode' => '73.26', 'nama' => 'Kabupaten Toraja Utara'],
            ['kode' => '73.71', 'nama' => 'Kota Makassar'],
            ['kode' => '73.72', 'nama' => 'Kota Parepare'],
            ['kode' => '73.73', 'nama' => 'Kota Palopo'],

            // 74 - SULAWESI TENGGARA (17)
            ['kode' => '74.01', 'nama' => 'Kabupaten Buton'],
            ['kode' => '74.02', 'nama' => 'Kabupaten Muna'],
            ['kode' => '74.03', 'nama' => 'Kabupaten Konawe'],
            ['kode' => '74.04', 'nama' => 'Kabupaten Kolaka'],
            ['kode' => '74.05', 'nama' => 'Kabupaten Konawe Selatan'],
            ['kode' => '74.06', 'nama' => 'Kabupaten Bombana'],
            ['kode' => '74.07', 'nama' => 'Kabupaten Wakatobi'],
            ['kode' => '74.08', 'nama' => 'Kabupaten Kolaka Utara'],
            ['kode' => '74.09', 'nama' => 'Kabupaten Buton Utara'],
            ['kode' => '74.10', 'nama' => 'Kabupaten Konawe Utara'],
            ['kode' => '74.11', 'nama' => 'Kabupaten Kolaka Timur'],
            ['kode' => '74.12', 'nama' => 'Kabupaten Konawe Kepulauan'],
            ['kode' => '74.13', 'nama' => 'Kabupaten Muna Barat'],
            ['kode' => '74.14', 'nama' => 'Kabupaten Buton Tengah'],
            ['kode' => '74.15', 'nama' => 'Kabupaten Buton Selatan'],
            ['kode' => '74.71', 'nama' => 'Kota Kendari'],
            ['kode' => '74.72', 'nama' => 'Kota Baubau'],

            // 75 - GORONTALO (6)
            ['kode' => '75.01', 'nama' => 'Kabupaten Boalemo'],
            ['kode' => '75.02', 'nama' => 'Kabupaten Gorontalo'],
            ['kode' => '75.03', 'nama' => 'Kabupaten Pohuwato'],
            ['kode' => '75.04', 'nama' => 'Kabupaten Bone Bolango'],
            ['kode' => '75.05', 'nama' => 'Kabupaten Gorontalo Utara'],
            ['kode' => '75.71', 'nama' => 'Kota Gorontalo'],

            // 76 - SULAWESI BARAT (6)
            ['kode' => '76.01', 'nama' => 'Kabupaten Pasangkayu'],
            ['kode' => '76.02', 'nama' => 'Kabupaten Mamuju'],
            ['kode' => '76.03', 'nama' => 'Kabupaten Mamasa'],
            ['kode' => '76.04', 'nama' => 'Kabupaten Polewali Mandar'],
            ['kode' => '76.05', 'nama' => 'Kabupaten Majene'],
            ['kode' => '76.06', 'nama' => 'Kabupaten Mamuju Tengah'],

            // 81 - MALUKU (11)
            ['kode' => '81.01', 'nama' => 'Kabupaten Maluku Tengah'],
            ['kode' => '81.02', 'nama' => 'Kabupaten Maluku Tenggara'],
            ['kode' => '81.03', 'nama' => 'Kabupaten Kepulauan Tanimbar'],
            ['kode' => '81.04', 'nama' => 'Kabupaten Buru'],
            ['kode' => '81.05', 'nama' => 'Kabupaten Seram Bagian Timur'],
            ['kode' => '81.06', 'nama' => 'Kabupaten Seram Bagian Barat'],
            ['kode' => '81.07', 'nama' => 'Kabupaten Kepulauan Aru'],
            ['kode' => '81.08', 'nama' => 'Kabupaten Maluku Barat Daya'],
            ['kode' => '81.09', 'nama' => 'Kabupaten Buru Selatan'],
            ['kode' => '81.71', 'nama' => 'Kota Ambon'],
            ['kode' => '81.72', 'nama' => 'Kota Tual'],

            // 82 - MALUKU UTARA (10)
            ['kode' => '82.01', 'nama' => 'Kabupaten Halmahera Barat'],
            ['kode' => '82.02', 'nama' => 'Kabupaten Halmahera Tengah'],
            ['kode' => '82.03', 'nama' => 'Kabupaten Kepulauan Sula'],
            ['kode' => '82.04', 'nama' => 'Kabupaten Halmahera Selatan'],
            ['kode' => '82.05', 'nama' => 'Kabupaten Halmahera Utara'],
            ['kode' => '82.06', 'nama' => 'Kabupaten Halmahera Timur'],
            ['kode' => '82.07', 'nama' => 'Kabupaten Pulau Morotai'],
            ['kode' => '82.08', 'nama' => 'Kabupaten Pulau Taliabu'],
            ['kode' => '82.71', 'nama' => 'Kota Ternate'],
            ['kode' => '82.72', 'nama' => 'Kota Tidore Kepulauan'],

            // 91 - PAPUA (9)
            ['kode' => '91.03', 'nama' => 'Kabupaten Jayapura'],
            ['kode' => '91.05', 'nama' => 'Kabupaten Kepulauan Yapen'],
            ['kode' => '91.06', 'nama' => 'Kabupaten Biak Numfor'],
            ['kode' => '91.10', 'nama' => 'Kabupaten Sarmi'],
            ['kode' => '91.11', 'nama' => 'Kabupaten Keerom'],
            ['kode' => '91.15', 'nama' => 'Kabupaten Waropen'],
            ['kode' => '91.19', 'nama' => 'Kabupaten Supiori'],
            ['kode' => '91.20', 'nama' => 'Kabupaten Mamberamo Raya'],
            ['kode' => '91.71', 'nama' => 'Kota Jayapura'],

            // 92 - PAPUA BARAT (7)
            ['kode' => '92.02', 'nama' => 'Kabupaten Manokwari'],
            ['kode' => '92.03', 'nama' => 'Kabupaten Fakfak'],
            ['kode' => '92.06', 'nama' => 'Kabupaten Teluk Bintuni'],
            ['kode' => '92.07', 'nama' => 'Kabupaten Teluk Wondama'],
            ['kode' => '92.08', 'nama' => 'Kabupaten Kaimana'],
            ['kode' => '92.11', 'nama' => 'Kabupaten Manokwari Selatan'],
            ['kode' => '92.12', 'nama' => 'Kabupaten Pegunungan Arfak'],

            // 93 - PAPUA SELATAN (4)
            ['kode' => '93.01', 'nama' => 'Kabupaten Merauke'],
            ['kode' => '93.02', 'nama' => 'Kabupaten Boven Digoel'],
            ['kode' => '93.03', 'nama' => 'Kabupaten Mappi'],
            ['kode' => '93.04', 'nama' => 'Kabupaten Asmat'],

            // 94 - PAPUA TENGAH (8)
            ['kode' => '94.01', 'nama' => 'Kabupaten Nabire'],
            ['kode' => '94.02', 'nama' => 'Kabupaten Puncak Jaya'],
            ['kode' => '94.03', 'nama' => 'Kabupaten Paniai'],
            ['kode' => '94.04', 'nama' => 'Kabupaten Mimika'],
            ['kode' => '94.05', 'nama' => 'Kabupaten Puncak'],
            ['kode' => '94.06', 'nama' => 'Kabupaten Dogiyai'],
            ['kode' => '94.07', 'nama' => 'Kabupaten Intan Jaya'],
            ['kode' => '94.08', 'nama' => 'Kabupaten Deiyai'],

            // 95 - PAPUA PEGUNUNGAN (8)
            ['kode' => '95.01', 'nama' => 'Kabupaten Jayawijaya'],
            ['kode' => '95.02', 'nama' => 'Kabupaten Pegunungan Bintang'],
            ['kode' => '95.03', 'nama' => 'Kabupaten Yahukimo'],
            ['kode' => '95.04', 'nama' => 'Kabupaten Tolikara'],
            ['kode' => '95.05', 'nama' => 'Kabupaten Mamberamo Tengah'],
            ['kode' => '95.06', 'nama' => 'Kabupaten Yalimo'],
            ['kode' => '95.07', 'nama' => 'Kabupaten Lanny Jaya'],
            ['kode' => '95.08', 'nama' => 'Kabupaten Nduga'],

            // 96 - PAPUA BARAT DAYA (6)
            ['kode' => '96.01', 'nama' => 'Kabupaten Sorong'],
            ['kode' => '96.02', 'nama' => 'Kabupaten Sorong Selatan'],
            ['kode' => '96.03', 'nama' => 'Kabupaten Raja Ampat'],
            ['kode' => '96.04', 'nama' => 'Kabupaten Tambrauw'],
            ['kode' => '96.05', 'nama' => 'Kabupaten Maybrat'],
            ['kode' => '96.71', 'nama' => 'Kota Sorong'],
        ];

        $now = date('Y-m-d H:i:s');
        $insertedCount = 0;
        $updatedCount = 0;

        foreach ($dataKabupaten as $item) {
            // Ambil 2 digit pertama kode kemendagri sebagai kode provinsi
            $kodeProv = substr($item['kode'], 0, 2);
            $provInfo = $provMap[$kodeProv] ?? null;

            $provinsiId   = $provInfo ? $provInfo['id'] : null;
            $provinsiNama = $provInfo ? $provInfo['nama'] : '';

            $existing = $builder->where('kode_kemendagri', $item['kode'])->get()->getRowArray();

            if ($existing) {
                $builder->where('id', $existing['id'])->update([
                    'provinsi_id'     => $provinsiId ?? $existing['provinsi_id'],
                    'nama'            => $item['nama'],
                    'provinsi'        => $provinsiNama ?: $existing['provinsi'],
                    'is_active'       => 1,
                    'updated_at'      => $now,
                ]);
                $updatedCount++;
            } else {
                $builder->insert([
                    'provinsi_id'     => $provinsiId,
                    'kode_kemendagri' => $item['kode'],
                    'nama'            => $item['nama'],
                    'provinsi'        => $provinsiNama,
                    'is_active'       => 1,
                    'created_at'      => $now,
                    'updated_at'      => $now,
                ]);
                $insertedCount++;
            }
        }

        echo "Kabupaten Seeder selesai: {$insertedCount} data baru ditambahkan, {$updatedCount} data diperbarui. Total: " . count($dataKabupaten) . " kabupaten/kota.\n";
    }
}
